apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      hostNetwork: true
      runtimeClassName: "crun"
      containers:
      - name: http-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: http
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: http
        resources:
           limits:
             memory: 32Mi
             cpu: 125m
           requests:
             memory: 32Mi
             cpu: 125m
