apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: "crun"
      containers:
      - name: http-server
        image: quay.io/uirlis/http_server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: http
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: http
        resources:
           limits:
             memory: 32Mi
             cpu: 125m
           requests:
             memory: 32Mi
             cpu: 125m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop : ["ALL"]
          seccompProfile:
            type : RuntimeDefault
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-cip
  labels:
    app: http-server
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: http-server
